/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about.vue')['default']
    CTA: typeof import('./src/components/CTA.vue')['default']
    CtaSection: typeof import('./src/components/CtaSection.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FooterSection: typeof import('./src/components/FooterSection.vue')['default']
    Founders: typeof import('./src/components/Founders.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    Howtop: typeof import('./src/components/Howtop.vue')['default']
    HowWorks: typeof import('./src/components/HowWorks.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Map: typeof import('./src/components/map.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Menuv: typeof import('./src/components/Menuv.vue')['default']
    PricingTable: typeof import('./src/components/PricingTable.vue')['default']
    Prime: typeof import('./src/components/prime.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServicesGrid: typeof import('./src/components/ServicesGrid.vue')['default']
    SkillsStats: typeof import('./src/components/SkillsStats.vue')['default']
    SuperTeam: typeof import('./src/components/SuperTeam.vue')['default']
    SystemScroll: typeof import('./src/components/SystemScroll.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Uslugi: typeof import('./src/components/Uslugi.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    WhyCool: typeof import('./src/components/WhyCool.vue')['default']
  }
}
